# Global fallback values
output_dir: /srv/backups
compression_lvl: 3
retention_days: 14
on_calendar: "*-*-* 11:30:00"
randomized_delay: 15m
persistent: true
owner: wyre

paths:
  - /etc
  - /usr/local/bin
  - /home/wyre/somefolder/id/like/tobackup

services:
  mc@fabric_kmz:
    dirs:
      - /home/wyre/mcserver/Fabric/fabric_kmz
    output_dir: /home/wyre/mcserver/backups
    exclude_patterns:
      - '*/dynmap/web/*'

  httpd:
    dirs:
      - /etc/httpd
      - /var/www
    output_dir: /srv/backups/httpd
    exclude_patterns:
      - '*.tmp'
    compression_lvl: 5
    retention_days: 21
    on_calendar: "*-*-* 03:15:00"
    randomized_delay: 5m
    persistent: true
    owner: root
    restart_after_backup: false
